# Generated by Django 4.0.6 on 2022-07-21 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField(verbose_name='release date')),
                ('price', models.IntegerField()),
                ('protectors', models.ManyToManyField(to='main_app.protector')),
            ],
        ),
        migrations.CreateModel(
            name='Worn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date worn')),
                ('place', models.CharField(choices=[('P', 'Play'), ('W', 'Work'), ('S', 'School'), ('C', 'Chill'), ('A', 'Athletics')], default='P', max_length=1)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sneaker')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
